Repository wazo-platform/wazo-platform.org, pull requests merged in 2020-04, with the labels that each got.

#154 Wazo 1560 webrtc line on import
  content/uc-doc/administration/users/csv_import.md
Labels: mergeit

#156 add an upgrade note for the transport name changes
  content/uc-doc/upgrade/upgrade_notes.md
Labels: mergeit

#158 remove ref to wazo-doc
  content/uc-doc/community/index.md
Labels: mergeit

#159 optimize build by not loading containers for testing
  Makefile
  docker-compose-tests.yml
  docker-compose.yml
Labels: auto-merge

#157 blog: add release 20.05
  content/blog/sprint-review-2005.md
Labels: mergeit

#160 deprecated auth TLS configuration
  content/uc-doc/contributors/network.md
  content/uc-doc/upgrade/upgrade_notes.md
Labels: mergeit

#164 blog: relase 20.06
  content/blog/sprint-review-2006.md
Labels: mergeit

#165 rename ctid-ng to calld
  content/sections.yaml
Labels: mergeit

#162 Add donate question
  content/contribute.md
  src/component/contribute/index.js
Labels: mergeit

#163 use pytest instead nose
  content/contribute/guidelines.md
  content/uc-doc/contributors/xivo_package_file_structure.md
Labels: auto-merge, mergeit

#166 doc: proxy: add setupd instructions and missing commands
  content/uc-doc/system/proxy.md
Labels: mergeit

#167 Removing table of content inside contributors pages
  content/uc-doc/contributors/contributing_to_wazo.md
  content/uc-doc/contributors/debug_asterisk.md
  content/uc-doc/contributors/debug_daemon.md
  content/uc-doc/contributors/diagrams.md
  content/uc-doc/contributors/guidelines.md
  content/uc-doc/contributors/index.md
  content/uc-doc/contributors/plugins.md
  content/uc-doc/contributors/profile_python.md
  content/uc-doc/contributors/provisioning/developing_plugins.md
  content/uc-doc/contributors/provisioning/index.md
  content/uc-doc/contributors/provisioning/managing_dhcp_server_configuration.md
  content/uc-doc/contributors/provisioning/testing_new_sip_phone.md
  content/uc-doc/contributors/sccp.md
  content/uc-doc/contributors/style_guide.md
  content/uc-doc/contributors/translate.md
  content/uc-doc/contributors/xivo_package_file_structure.md
Labels: mergeit

#168 doc: install: ansible group names have changed
  content/uc-doc/installation/install-system.md
Labels: mergeit
