Repository wazo-platform/wazo-platform.org, pull requests merged in 2020-10, with the labels that each got.

#230 upgrade dependencies
  src/component/LayoutPlatform.js
  yarn.lock
Labels: mergeit

#233 asterisk debug: remove the old table and add text
  content/uc-doc/contributors/debug_asterisk.md
Labels: auto-merge

#239 sed s/wazopbx/wazoplatform/
  content/agentd/core.md
  content/auth/admin.md
  content/plugind/admin.md
Labels: auto-merge, mergeit

#240 Pull request for WAZO-2017-rename-wazo-stat
  content/uc-doc/administration/call_logs/index.md
  content/uc-doc/contact_center/reporting.md
  content/uc-doc/system/log_files.md
  content/uc-doc/upgrade/upgrade_notes.md
Labels: mergeit

#241 update the reporting page
  content/uc-doc/contact_center/reporting.md
  static/images/uc-doc/contact_center/reporting/archi.png
Labels: mergeit

#242 Fix upgrade sections
  content/uc-doc/upgrade/index.md
  content/uc-doc/upgrade/old_upgrade_notes.md
  content/uc-doc/upgrade/upgrade_notes.md
  content/uc-doc/upgrade/upgrade_notes_details/18-01/index.md
  content/uc-doc/upgrade/upgrade_notes_details/18-01/stretch.md
  content/uc-doc/upgrade/upgrade_notes_details/18-12/asterisk_16.md
  content/uc-doc/upgrade/upgrade_notes_details/18-12/index.md
  content/uc-doc/upgrade/upgrade_notes_details/19-03/index.md
  content/uc-doc/upgrade/upgrade_notes_details/19-03/sounds.md
  content/uc-doc/upgrade/upgrade_notes_details/19-13/buster.md
  content/uc-doc/upgrade/upgrade_notes_details/19-13/index.md
  content/uc-doc/upgrade/upgrade_notes_details/index.md
Labels: mergeit

#243 Pull request for fix-system-sections-part1
  content/uc-doc/system/backup_restore.md
  content/uc-doc/system/configuration_files.md
  content/uc-doc/system/https_certificate.md
Labels: mergeit

#245 add release 20.14
  content/blog/sprint-review-2014.md
Labels: mergeit
