Repository wazo-platform/wazo-platform.org, pull requests merged in 2021-05, with the labels that each got.

#337 Pull request for fix-links
  content/uc-doc/administration/index.md
  content/uc-doc/administration/interconnections/wazo_with_pbx.md
  content/uc-doc/administration/provisioning/adv_configuration.md
  content/uc-doc/api_sdk/index.md
  content/uc-doc/api_sdk/rest_api/conventions.md
  content/uc-doc/api_sdk/rest_api/reference.md
  content/uc-doc/contributors/debug_asterisk.md
  content/uc-doc/contributors/index.md
  content/uc-doc/contributors/profile_python.md
  content/uc-doc/contributors/sccp.md
  content/uc-doc/system/index.md
  content/uc-doc/system/wazo-sysconfd.md
  content/uc-doc/troubleshooting/index.md
Labels: auto-merge, mergeit

#338 Fix URL to Supported Devices
  src/component/provisioning/phone.js
  src/component/provisioning/vendor.js
Labels: mergeit

#340 refresh token: remove expiration from example
  content/blog/wazo-auth-refresh-token.md
Labels: mergeit

#341 upgrade notes: older recordings are not removed automatically.
  content/uc-doc/upgrade/upgrade_notes.md
Labels: mergeit

#344 Pull request for improve-doc
  content/uc-doc/administration/index.md
  content/uc-doc/api_sdk/rest_api/acl.md
  content/uc-doc/api_sdk/rest_api/changelog.md
  content/uc-doc/api_sdk/rest_api/conventions.md
  content/uc-doc/api_sdk/rest_api/examples.md
  content/uc-doc/api_sdk/rest_api/quickstart.md
  content/uc-doc/api_sdk/rest_api/reference.md
  content/uc-doc/api_sdk/rest_api/troubleshooting.md
  content/uc-doc/contributors/index.md
  content/uc-doc/troubleshooting/index.md
  content/uc-doc/upgrade/upgrade_notes_details/18-01/stretch.md
  src/component/LayoutPlatform.js
Labels: mergeit

#347 21.06: sprint review
  content/blog/sprint-review-2106.md
Labels: mergeit

#349 Re-encrypt key without trimming
  zuul.yaml
Labels: auto-merge

#339 Pull request for WAZO-2154-remove-deprecated-before-17-01
  content/uc-doc/administration/provisioning/adv_configuration.md
  content/uc-doc/api_sdk/message_bus.md
  content/uc-doc/contributors/debug_asterisk.md
  content/uc-doc/upgrade/introduction.md
  content/uc-doc/upgrade/old_upgrade_notes.md
  content/uc-doc/upgrade/upgrade_notes_details/16-16/asterisk_14.md
  content/uc-doc/upgrade/upgrade_notes_details/16-16/index.md
  content/uc-doc/upgrade/upgrade_notes_details/16-16/xivo_to_wazo.md
  content/uc-doc/upgrade/upgrade_specific_version/archives-from-wazo-jessie.md
  content/uc-doc/upgrade/upgrade_specific_version/archives-from-xivo.md
  content/uc-doc/upgrade/upgrade_specific_version/index.md
  content/uc-doc/upgrade/upgrade_specific_version/introduction.md
  content/uc-doc/upgrade/version_deprecation_policy.md
Labels: mergeit

#350 Pull request for improve-doc
  content/uc-doc/api_sdk/rest_api/conventions.md
  content/uc-doc/upgrade/old_upgrade_notes.md
  content/uc-doc/upgrade/upgrade_notes.md
Labels: mergeit

#313 fix file name in echo_canceller.md
  content/uc-doc/administration/hardware/echo_canceller.md
Labels: mergeit

#352 Pull request for fix-jira-links
  content/blog/introducing-wazo.md
  content/blog/new-community-forum.md
  content/blog/sprint-review-1616.md
  content/blog/sprint-review-1701.md
  content/blog/sprint-review-1702.md
  content/blog/sprint-review-1703.md
  content/blog/sprint-review-1704.md
  content/blog/sprint-review-1705.md
  content/blog/sprint-review-1706.md
  content/blog/sprint-review-1707.md
  content/blog/sprint-review-1708.md
  content/blog/sprint-review-1709.md
  content/blog/sprint-review-1710.md
  content/blog/sprint-review-1711.md
  content/blog/sprint-review-1712.md
  content/blog/sprint-review-1713.md
  content/blog/sprint-review-1714.md
  content/blog/sprint-review-1715.md
  content/blog/sprint-review-1716.md
  content/blog/sprint-review-1717.md
  content/blog/sprint-review-1801.md
  content/blog/sprint-review-1802.md
  content/blog/sprint-review-1803.md
  content/blog/sprint-review-1915.md
  content/blog/sprint-review-1916.md
  content/blog/sprint-review-1917.md
  content/blog/sprint-review-2001.md
  content/blog/sprint-review-2002.md
  content/blog/sprint-review-2003.md
  content/blog/sprint-review-2004.md
  content/blog/sprint-review-2005.md
  content/blog/sprint-review-2006.md
  content/blog/sprint-review-2007.md
  content/blog/sprint-review-2008.md
  content/blog/sprint-review-2009.md
  content/blog/sprint-review-2010.md
  content/blog/sprint-review-2011.md
  content/blog/sprint-review-2012.md
  content/blog/sprint-review-2013.md
  content/blog/sprint-review-2014.md
  content/blog/sprint-review-2015.md
  content/blog/sprint-review-2016.md
  content/blog/sprint-review-2017.md
  content/provd/admin.md
Labels: auto-merge, mergeit

#353 fix broken links
  content/uc-doc/upgrade/upgrade_notes_details/18-01/index.md
  content/uc-doc/upgrade/upgrade_notes_details/18-12/index.md
  content/uc-doc/upgrade/upgrade_notes_details/19-03/index.md
  content/uc-doc/upgrade/upgrade_notes_details/19-13/index.md
Labels: auto-merge, mergeit

#354 Pull request for improve-doc
  content/uc-doc/api_sdk/rest_api/confd/user_import.md
  content/uc-doc/api_sdk/rest_api/sysconfd/asterisk_voicemail.md
  content/uc-doc/api_sdk/rest_api/sysconfd/common_configuration.md
  content/uc-doc/api_sdk/rest_api/sysconfd/dhcpd_configuration.md
  content/uc-doc/api_sdk/rest_api/sysconfd/dns.md
  content/uc-doc/api_sdk/rest_api/sysconfd/ha.md
  content/uc-doc/api_sdk/rest_api/sysconfd/handlers.md
  content/uc-doc/api_sdk/rest_api/sysconfd/services.md
  content/uc-doc/api_sdk/rest_api/sysconfd/status_check.md
  content/uc-doc/api_sdk/rest_api/sysconfd/xivo_services.md
  content/uc-doc/api_sdk/rest_api/webhookd/index.md
  content/uc-doc/api_sdk/rest_api/webhookd/templates.md
  content/uc-doc/api_sdk/rest_api/webhookd/user_filter.md
Labels: mergeit

#356 remove IRC link
  src/component/LayoutPlatform.js
Labels: mergeit

#360 Pull request for upgrade-note-21-07
  content/uc-doc/upgrade/upgrade_notes.md
Labels: auto-merge, mergeit

#359 21.07: sprint review
  content/blog/sprint-review-2107.md
Labels: auto-merge, mergeit
