Repository wazo-platform/wazo-platform.org, pull requests merged in 2021-09, with the labels that each got.

#393 add 21.12 upgrade notes
  content/uc-doc/upgrade/upgrade_notes.md
Labels: auto-merge

#394 sprint review 21.12
  content/blog/sprint-review-2112.md
Labels: mergeit

#395 quickstart: fix styling issue
  content/uc-doc/api_sdk/rest_api/quickstart.md
Labels: mergeit, self-approve

#392 CDR Machine learning Article
  content/blog/value-your-cdr-with-machine-learning.md
Labels: mergeit

#396 Pull request for blog-machine-learning-typos
  content/blog/value-your-cdr-with-machine-learning.md
Labels: mergeit, auto-merge

#398 zuul: fix notification
  zuul.d/notification.yml
Labels: mergeit, auto-merge

#400 Auto merge
  zuul.yaml
Labels: mergeit, auto-merge

#399 blog: fix machine learning images
  content/blog/value-your-cdr-with-machine-learning.md
  static/images/blog/machine-learning/neural-net.png
  static/images/blog/machine-learning/scikit.png
Labels: mergeit, auto-merge

#401 blog: fix machine learning image
  content/blog/value-your-cdr-with-machine-learning.md
  static/images/blog/machine-learning/flask.png
Labels: mergeit, auto-merge

#214 add documentation for basic NAT setup
  content/uc-doc/administration/index.md
  content/uc-doc/administration/nat.md
  content/uc-doc/contributors/provisioning/nat_environment.md
Labels: mergeit

#403 doc: install: fix missing lines in code blocks
  content/uc-doc/installation/install-system.md
Labels: mergeit, auto-merge

#404 Fix `header` class conflicts between header and code hightlight
  src/styles/corporate/devaid.scss
  src/styles/corporate/pretty-docs.scss
  src/styles/corporate/styles.scss
  src/styles/platform/devaid.scss
  src/styles/platform/pretty-docs.scss
Labels: mergeit

#405 add BETA note on class-4 install
  content/install-c4.md
Labels: mergeit

#406 remove broken digium links
  content/blog/sprint-review-1715.md
  content/uc-doc/administration/hardware/pri_configuration.md
Labels: mergeit
